project:
  title: template-computo-quarto
  render: 
    - template-computo-quarto.qmd
  resources: 
    - environment.yml
    - .nojekyll

execute: 
  cache: true
  freeze: auto

format:
  computo-html: 
    output-file: index.html
  computo-pdf: default  