name: build
on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
      - main

env: # Change this if needed
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  computorticle:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Installing dependencies with Micromamba
        uses: mamba-org/provision-with-micromamba@v16
        with:
          cache-env: true

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Rendering with Quarto
        uses: quarto-dev/quarto-actions/render@v2          

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          branch: gh-pages
          clean: true
