name: build
on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
      - main

jobs:
  computorticle:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4

      - name: Cache micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true

      - name: Install Computo extension for Quarto + libertinus hack
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension
            ~/.TinyTeX/bin/x86_64-linux/tlmgr install libertinus-fonts

      - name: install system dependencies
        run: sudo apt update && sudo apt install -y libharfbuzz-dev libfribidi-dev libcurl4-openssl-dev

      - name: register micromamba for reticulate
        shell: micromamba-shell {0}
        run: echo RETICULATE_PYTHON=`which python` > _environment

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
